### ISSUE TITLE
TLS support with SSLContext not working

### ISSUE THREAD

**Issue by nicojs** [finagle/finch#757] opened 2017-03-16 11:35 UTC
Starting a web server with TLS enabled doesn't seem to work when using an SSL context (haven't tried with certificate path and key path).

I've prepared an example which reproduces this problem here: https://github.com/nicojs/poc-finch-tls

Basically we're doing this:

```scala
  def getSSLContext: SSLContext = {
    /*
    omitted for clarity
    */
    val sslContext = SSLContext.getInstance("TLS")
    sslContext.init(kmf.getKeyManagers, tmf.getTrustManagers, null)
    sslContext
  }

  val server = Http.server
    .withTransport.tls(getSSLContext)
    .serve(s":38082", routes/*...*/.toService)
```

The server seems to just *totally ignore* the fact that we ask for TLS transport security and just provides the server over plain http.

This is demonstrated by the following output:

```
$ openssl s_client -showcerts -servername localhost -connect localhost:3808
CONNECTED(00000003)
140433661974160:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:782:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 307 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1489663087
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Any ideas on why this is happening?

Any thoughts much appreciated!

**Comment by spockz** [comment] 2017-03-16 12:04
This has more to do with Finagle itself than with Finch. Which versions are you using?

**Comment by DieBauer** [comment] 2017-03-16 12:14
Used versions are 

```
libraryDependencies += "com.twitter" %% "finagle-http" % "6.42.0"
libraryDependencies += "com.github.finagle" %% "finch-core" % "0.13.1"
```

**Comment by rpless** [comment] 2017-03-16 12:42
I agree this is a Finagle thing. Out of curiosity did you try Vladimir's suggestion from gitter of using it on port 443?

**Comment by nicojs** [comment] 2017-03-16 13:48
We've just got a major breakthrough! Turning netty4 on seems to solve it:

```
  val server = Http.server
    .withTransport.tls(getSSLContext)
    .configured(Http.Netty4Impl)
    .serve(s":38082", routes.handle {
      case e: Exception =>
        InternalServerError(e)
    }.toService)

  println("Server running on :38082")
  Await.result(server)
```

Is this by design somehow? Any ideas on whats going on here would be wonderful.

**Comment by spockz** [comment] 2017-03-16 15:11
I'm not sure what exactly is going on but a recent discussion on Gitter hinted on things being reworked for netty4. Maybe some things broke for netty3 in the process?

**Comment by vkostyukov** [comment] 2017-03-16 16:30
@nicojs It's not by design. Both versions (Netty 3 and Netty 4) should work just fine. The only difference between those two is that N3 will use JDK SSL implementation and N4 will try to do OpenSSL first.

**Comment by BenWhitehead** [comment] 2017-03-16 17:36
I spent some time figuring out the args to get this to work for my project finch-server.

Here is the code I ended up with to bootstrap an `Http.server` with TLS support. https://github.com/BenWhitehead/finch-server/blob/master/src/main/scala/io/github/benwhitehead/finch/FinchServer.scala#L146 

(When I wrote this code it was back against `"com.twitter" %% "finagle-http" % "6.31.0"` which was only netty3. I have verified that the config works up to finagle 6.33.0, but I have not yet tried it against finagle 6.42.0. Just thought I would add a reference to see if it could help you out.)

**Comment by nicojs** [comment] 2017-03-17 08:59
@BenWhitehead thanks for your comment! We've seen that project and tried it, but we really need to build our own SSLContext. 

@vkostyukov so this is an actual bug? Or are we doing something wrong? Maybe not using the JDK SLL implementation or something?

**Comment by vkostyukov** [comment] 2017-03-17 17:14
It might be a bug since I'm not sure we use `SSLContext` internally. I'm going to try to reproduce it and then file an internal issue if it's confirmed.

**Comment by vkostyukov** [comment] 2017-03-17 17:40
Funny story (kudos @ryanoneill for helping me to figure this out).

Turns out that configuration method (`withTransport.tls(SSLConext)`) was never supported on Netty 3 and, in fact, there is [a note in the Scala doc about that](https://twitter.github.io/finagle/docs/com/twitter/finagle/param/ServerTransportParams.html#tls(context:javax.net.ssl.SSLContext):A). Even though there is a way to configure SSLContext in Netty 3 (using slightly different API), I'd recommend staying on Netty 4 since it's just where finagle-http is moving at the moment.


This inconsistency is [already fixed in Finagle's master](https://github.com/twitter/finagle/commit/4f7fbedf9dbb4cabcb529dd523a3cc9696f7fbaa#diff-d67679c663db660b37c755094fc34accL72) and will be released in a month of so.

**Closed** 2017-03-17 17:41 UTC
