### ISSUE TITLE
Server hangs on endpoints

### ISSUE THREAD

**Issue by acidghost** [finagle/finch#1086] opened 2019-02-19 08:25 UTC
```scala
import $ivy.`com.github.finagle::finchx-core:0.27.0`

import cats.effect.IO
import io.finch._
import io.finch.catsEffect._
import com.twitter.finagle.Http
import com.twitter.util.Await
import shapeless._


val e0 = get("path" :: path[Long]) { id: Long => Ok(id.toString) }

val endpoint: Endpoint[IO, String] =
  post("path" :: multipartFileUpload("pic")).mapOutput(fu => Ok(fu.fileName))

val service = Bootstrap.configure().serve[Text.Plain](e0 :+: endpoint).toService

val server = Http.server.serve(":1337", service)

Await.result(server)
```

Simple valid requests hang indefinitely with no output (`curl -vvvv http://localhost:1337/path/1` and `curl -vvvv -F "pic=@500.png;type=image/png" http://localhost:1337/path`).

Moreover if I change `endpoint` to `put(...)` I always get 400 missing `pic` param.

**Comment by vkostyukov** [comment] 2019-02-19 17:39
Hm. @acidghost I tried your exact reproducer on master and it all works for me as expected:

```
$ curl -vvvv http://localhost:1337/path/1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1337 (#0)
> GET /path/1 HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 19 Feb 2019 17:33:35 GMT
< Server: Finch
< Content-Length: 1
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
$ curl -vvvv -F "pic=@500.png;type=image/png" http://localhost:1337/path
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1337 (#0)
> POST /path HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/7.59.0
> Accept: */*
> Content-Length: 123596
> Content-Type: multipart/form-data; boundary=------------------------c72e1138bfa5a776
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Date: Tue, 19 Feb 2019 17:35:51 GMT
< Server: Finch
< Content-Length: 7
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
500.png
```

Going to try this against 0.27 tag as well.

**Comment by vkostyukov** [comment] 2019-02-21 00:59
@acidghost I tried tag v0.27.0 and it still works as expected. Maybe there is something else in your setup that gets in a way. What's your .png file size?

**Comment by acidghost** [comment] 2019-02-21 06:25
@vkostyukov it's 1.5kb...

![500](https://user-images.githubusercontent.com/1787979/53148031-ad9cf280-35a9-11e9-822c-85fa2789e234.png)

**Comment by vkostyukov** [comment] 2019-02-21 16:48
I tried this file as well - all fine on 0.27.0 tag. Are you sure there are no other endpoints in your service when you try to reproduce it locally? Any firewalls? Any chance you can wireshark your localhost interface to get a better idea what's going on?

**Comment by vkostyukov** [comment] 2019-02-25 17:59
@acidghost Were you able to figure out what's going on with your server?

**Comment by vkostyukov** [comment] 2019-02-27 21:33
@acidghost Please reach out again if that's still a problem for you.

**Comment by acidghost** [comment] 2019-03-03 13:07
@vkostyukov finally found some time to investigate a bit. No firewall or any particular configuration on Ubuntu 16.04.6, kernel 4.13.16.
Wireshark did non reveal anything in particular: the server acknowledges the http request and then remains silent (expects a query param that is not there and should return 400)

**Comment by rpless** [comment] 2019-03-03 14:55
> Moreover if I change endpoint to put(...) I always get 400 missing pic param.

When we attempt to decode a multipart request we call Finagle's `MultipartDecoder.decode`, which in turn calls a function called`isMultipart` which seems only considers [POST requests to be multipart](https://github.com/twitter/finagle/blob/b8523a4541953d6bbc6a64b9409d75ff162afcd9/finagle-base-http/src/main/scala/com/twitter/finagle/http/exp/MultipartDecoder.scala#L39). I suspect `PUT` requests won't work here.

I'm seeing the same thing that @vkostyukov did when the endpoint is a `POST` though.

**Comment by vkostyukov** [comment] 2019-03-04 01:47
@acidghost Do you run the exact same code as in the REPL snippet in this ticket? Or is it just similar to that?

**Comment by acidghost** [comment] 2019-03-06 12:50
Exact same

**Comment by vkostyukov** [comment] 2019-03-06 16:21
@acidghost I wish we could help you but it's somewhat hard without being able to reproduce it. If you can make some progress on your own (I know you already looked at the wireshark, so I'd probably try to attach a debugger and see where it hangs) and report back your findings, maybe we can help better.

I will close this for now but feel free to open when you find something.

**Closed by vkostyukov** 2019-03-06 16:21 UTC
Labels: bug
