### ISSUE TITLE
Fix warnings from Wartremover

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#200] opened 2015-02-19 17:06 UTC
We enabled Wartremoved in #199. For now it produces around 100 warnings. It would be nice if we can fix them and change the level from warning to error to prevent new things.

This is a perfect issue for newcomers. It's not necessary to fix all the warnings in one PR. The best idea would be to fix them file-by-file.

**Comment by nicmart** [comment] 2015-03-22 16:12
Hi all, I love scala and in particular this project, and I am happy to start contributing with these "easy" issues, since I am quite new to the language.

I have just fixed a couple of "inferred type containing Nothing" warnings in RequestReader.

Now I am just wondering how to fix the problem "Function has default arguments", since removing default arguments changes the api, and so it's not BC compatible.

**Comment by vkostyukov** [comment] 2015-03-23 22:43
Well. I think we can leverage between sane and super-functional approach. Default arguments is the most arguable wart in WartRemover (there is [an epic ticket](https://github.com/puffnfresh/wartremover/issues/116) about it). Let's just disable this wart for now and keep default args in Finch.

**Comment by nicmart** [comment] 2015-03-24 14:05
Ok, as soon I have time I will go on with the other fixes, disabling the wart for default args.

**Comment by nicmart** [comment] 2015-04-06 15:48
There are a lot of "isInstanceOf is disabled" errors in simple pattern matches, like in this
```
[warn] /www/finch/core/src/main/scala/io/finch/route/Router.scala:100: isInstanceOf is disabled
[warn]       case (aa @ Some((a, _)), bb @ Some((b, _))) =>
[warn]                      ^
```
How to solve this? It looks to me like a normal pattern matching, maybe I'm missing something?

**Comment by vkostyukov** [comment] 2015-04-06 15:59
Internally pattern `Some(a)` looks like `a: Some[_]`, so it's till uses is instance of. Perhaps, we can also skip this check.

**Comment by travisbrown** [comment] 2015-04-06 16:10
This looks like a bug in WartRemover—there definitely will be a synthetic `isInstanceOf` here, but it's safe (not actually type-case). Here's a quick stab at a minimization:

``` scala
// fine, no warning
(Some(1): Option[Int]) match { case x @ Some(_) => x }
```

``` scala
// blows up with "isInstanceOf is disabled"
((Some(1), 'a'): (Option[Int], Char)) match { case (x @ Some(_), _) => x }
```

At a glance at WartRemover I don't see why there's a difference here, or any open issues that report this.

**Comment by vkostyukov** [comment] 2015-04-06 16:14
Hm. This is nice. Maybe the difference is that we match over two layers instead (tupple -> option)? Maybe test `Some(Some(1)) match { .. }` will confirm it.

**Comment by travisbrown** [comment] 2015-04-06 16:18
The following doesn't get the warning, so it looks like the tuple and `Some` are interacting somehow:

``` scala
(Some(Some(1)): Option[Option[Int]]) match { case x @ Some(Some(_)) => x }
```

I'm going to spend ten minutes looking into this and then just report it if I can't tell what's up.

**Comment by vkostyukov** [comment] 2015-04-06 16:19
Awesome! Thank you @travisbrown! At lest it fit well into a FixItWeek :)

**Comment by travisbrown** [comment] 2015-04-06 16:35
Okay, [reported](https://github.com/puffnfresh/wartremover/issues/152). Doesn't look like there's a trivial solution, unfortunately.

**Comment by nicmart** [comment] 2015-04-06 19:08
Thanks @travisbrown!

I've ran into another problem in the Json package, I get a lot of "Inferred type Any" just because Json case classes have the Any type in the constructor arguments. I don't think that is the expected behavior for the Any check.

I've already [reported](https://github.com/puffnfresh/wartremover/issues/153) the problem.

**Comment by nicmart** [comment] 2015-04-12 19:12
Hi all,
I think I have finished at least what I could do...
Summarizing, the remaining warnings are:
1. Some false `isInstanceOf` warnings due to https://github.com/puffnfresh/wartremover/issues/152
2. A lot of `Inferred type containing Any` in the Json package, see [this issue](https://github.com/puffnfresh/wartremover/issues/153). It is not clear if that rule should allow Any in some signatures or not, but for sure its behavior is inconsistent.
3. Some `Statements must return Unit` due to mutable expressions like `map += (id -> u)`in a statement position.

The rest of the warnings should be fixed, let me know how to proceed for the above points.
Thanks!

**Comment by vkostyukov** [comment] 2015-07-10 16:52
I think this may be closed already. We're pretty good here.

**Closed** 2015-07-10 16:52 UTC
Labels: cleanup, easy
