### ISSUE TITLE
Cannot compile class using Finch with Scala 2.11 (Maven)

### ISSUE THREAD

**Issue by richiesgr** [finagle/finch#866] opened 2017-11-13 17:38 UTC
Hi

I'm trying to write this
 ```
 def div: Endpoint[Int] = post(path[Int] :: path[Int]) { (a: Int, b: Int) =>
    val rr = a /b
    Ok(rr)
  } handle {
    case e: ArithmeticException => BadRequest(e)
  }

  def test2: Endpoint[Int] = get("test" :: path[Int]) { a: Int =>
    Ok(1)
  } handle {
    case e: ArithmeticException => BadRequest(e)
  }
```
The first Endpoint compile the second I get 3 errors

```
Error:(36, 64) type mismatch;
 found   : io.finch.Endpoint[Int]
 required: Int
  def test2: Endpoint[Int] = get("test" :: path[Int]) { a: Int =>

Error:(36, 64) type mismatch;
 found   : io.finch.Output[Int]
 required: ((e: io.finch.Endpoint[Int])io.finch.Endpoint[_9.Out]) forSome { val _9: io.finch.syntax.Mapper[Int] }
  def test2: Endpoint[Int] = get("test" :: path[Int]) { a: Int =>

Error:(36, 64) Could not derive subclass of io.finch.syntax.Mapper[Int]
 (with SAM `def method apply((e: io.finch.Endpoint[Int])io.finch.Endpoint[_9.Out]) forSome { val _9: io.finch.syntax.Mapper[Int] }`)
 based on: ((a: Int) => Ok(1)).
  def test2: Endpoint[Int] = get("test" :: path[Int]) { a: Int =>
```

Working with 2.12

Totally lost Now
Thanks

**Comment by ImLiar** [comment] 2017-11-13 21:07
Hi @richiesgr 

Could you provide a reproducible example of this failure? All the imports, the version you're using, ideally git repo?

Because it works for me normally

**Comment by ImLiar** [comment] 2017-11-13 21:17
Hi @richiesgr 

Could you provide a reproducible example of this error? With all the imports, fixed version, ideally git repo? 

Because for me it works fine on 2.11 and 2.12

**Comment by richiesgr** [comment] 2017-11-14 09:04
Hi
here is the github [repository](https://github.com/inneractive-opensrc/hermes)
look at the branch called inneractive-events
Thanks

**Comment by vkostyukov** [comment] 2017-11-14 17:34
So what's interesting is this is a Maven project. Do we know what Scala compiler Maven is using?

**Comment by vkostyukov** [comment] 2017-11-14 17:47
I actually can't compile it with `mvn` (assuming `mvn compile` is what need to do):

```
[ERROR] Failed to execute goal on project hermes: Could not resolve dependencies for project com.inneractive:hermes:jar:1.0.0: Failed to collect dependencies at com.ovoenergy:kafka-serialization-avro4s_2.11:jar:LATEST: Failed to read artifact descriptor for com.ovoenergy:kafka-serialization-avro4s_2.11:jar:LATEST: Failed to resolve version for com.ovoenergy:kafka-serialization-avro4s_2.11:jar:LATEST: Could not find metadata com.ovoenergy:kafka-serialization-avro4s_2.11/maven-metadata.xml in local (/Users/vkostyukov/.m2/repository) -> [Help 1]
```

**Comment by richiesgr** [comment] 2017-11-14 21:28
Sorry about this I'll try to fix it and push tomorrow
Thanks for the support

**Comment by richiesgr** [comment] 2017-11-15 14:55
Hi
Sorry for the delay I've fixed all the dependency issue and now you can pull and see only the error relative to finch
Thanks

**Comment by richiesgr** [comment] 2017-11-15 14:57
By the way Maven use a Plugin to compile scala code in pom.xml file you can see

      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.2.1</version>
        <configuration>
          <args>
            
            <arg>-Xexperimental</arg>
          </args>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

may be there is some params for the compiler that are default in sbt and not for the maven plugin

**Comment by ImLiar** [comment] 2017-11-15 17:42
Huh, it sounds like SAM takes a precedence over implicit conversion (well, it should) and fails to compile. Could you try to disable `-Xexperimental`?

**Comment by richiesgr** [comment] 2017-11-16 08:34
Ok If I remove the flag the finch code compile but a lot of other stuff from other framework doesn't so this is not a good solution

**Comment by ImLiar** [comment] 2017-11-16 13:51
@richiesgr try to update Scala to 2.11.12

**Comment by richiesgr** [comment] 2017-11-21 12:14
@ImLiar 
Already tried not working

**Comment by vkostyukov** [comment] 2017-11-22 00:08
I tried it in SBT (including the `-Xexperimental` option) and everything works fine (so it seems like a Maven problem for me):

```scala

$ sbt ++2.11.11 console

scala> :set -Xexperimental

scala> :paste
// Entering paste mode (ctrl-D to finish)

def test2: Endpoint[Int] = get("test" :: path[Int]) { a: Int =>
   Ok(1)
 } handle {
   case e: ArithmeticException => BadRequest(e)
 }

// Exiting paste mode, now interpreting.

test2: io.finch.Endpoint[Int]
```

**Comment by vkostyukov** [comment] 2018-01-19 19:00
@richiesgr Did you figure out how to unblock yourself?

**Comment by vkostyukov** [comment] 2018-03-19 21:42
Hey @richiesgr, I'm going to close this for now. Let us know if you're still blocked by this.

**Closed by vkostyukov** 2018-03-19 21:42 UTC
Labels: question
